name: Deploy to Aruba via FTP

on:
  push:
    branches:
      - main
  schedule:
    # Esegui ogni giorno alle 3:00 AM UTC (puoi modificare l'orario come preferisci)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Aggiunto per abilitare l'avvio manuale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the project
      run: |
        npm install
        npm run build # Adatta il comando al tuo progetto

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v5 # Usa la versione più recente
      with:
        server: ftp://ftp.filippomorano.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build
        server-dir: /www.filippomorano.com/projects/m2m-rdf
